### PR TITLE
Feature/session

### PR DESCRIPTION
**Pull request by DraagrenKirneh**
Refactor connection property into session variable which keeps track of the current connection session as well.
Usefull when dealing with prepared statements which are only available to the current session.

### CODE REVIEW

**Comment by svenvc** [comment]
The change is OK, but wouldn't the backend_process_id which is in the properties when connected not be a better and more meaningful identifier than an opaque UUID ?

I am not 100% sure, but I think a backend_process_id maps 1-to-1 to each connection.

**Comment by DraagrenKirneh** [comment]
Yes, good point.
Yeah looks like the map is 1 to 1:
```Smalltalk
(1 to: 10) collect: [ :x |
	(P3Client url: connectionString) connect; session
] "#(13036 888 6624 6492 12520 13056 12828 4980 4560 10580)"
```

**Comment by svenvc** [comment]
I guess #setSession can be removed now ?

**Comment by DraagrenKirneh** [comment]
argh, yes good catch thx.
I have not figured out how to deal with cypress format in an easy way so my current workflow is "commit" to a custom folder with iceberg and then copy the package items to the correct git repo, which does not account for deleted files...
Fixed now

**Comment by svenvc** [comment]
Works all fine on my end. Thank you

**Pull request merged**
